version: '3'
services:
    kong-database:
        container_name: kong-database
        image: postgres:9.5
        environment:
        - POSTGRES_USER=kong
        - POSTGRES_DB=kong
        volumes:
        - ./data/postgresql:/var/lib/postgresql/data
    kong:
        container_name: kong
        build:
            context: kong
        links:
        - kong-database:kong-database
        ports:
        - "9000:8000"
        - "9443:8443"
        - "9001:8001"
        - "9444:8444"
        environment:
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
        - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-bundle.crt
        - KONG_LOG_LEVEL=debug
        - KONG_PROXY_ACCESS_LOG=/dev/stdout
        - KONG_ADMIN_ACCESS_LOG=/dev/stdout
        - KONG_PROXY_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_ERROR_LOG=/dev/stderr
        - KONG_ADMIN_LISTEN=0.0.0.0:8001
        - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
        - KONG_CUSTOM_PLUGINS=oidc,okta-auth
        depends_on:
        - kong-database
    webapp:
        container_name: webapp
        build:
            context: webapp
        environment:
        - POSTGRES_USER=kong
        - POSTGRES_DB=kong
        volumes:
        - ./data/postgresql:/var/lib/postgresql/data        